###   配置JDBC相关信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: root
    password: stylcq
    type: com.alibaba.druid.pool.DruidDataSource
    ###   配置Druid相关信息
    druid:
      min-idle: 3
      max-active: 15
      initial-size: 5
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
###   mybatis相关信息
mybatis:
  mapper-locations: classpath*:/mapper/*.Mapper.xml
  type-aliases-package: tt.stylcq.pojo.entity